### ISSUE TITLE
Suggestion: setting global: 'window' instead of {}

### ISSUE THREAD

**Issue by jaybhum** [aws-samples/websocket-api-cognito-auth-sample#25]
I have found this demo you made to be tremendously helpful for my project that combines the AWS backend stack + Phaser front-end. Thank you very much!

I have one suggestion for a small part of your code that might be able to help others in a similar boat as me.

In your vite.config, you defined global: {}.
While this is necessary for AWS Authenticator to work properly and works fine for building this app, I noticed this would cause building my app with Phaser to crash because Phaser.js has, somewhere in its lines, a declaration that involves global.somethingsomething. 

I managed to get around this issue by declaring global: 'window' .

It took me a couple of hours of searching the internet to figure this out. I am pretty new to this space, maybe that is why and this is glaringly obvious to the pros out there, but I thought this might save some poor souls who are noobs like me :)

**Comment by tmokmss** [comment]
Hi @jaybhum, thank you for reporting this! I think you are right and it should make more sense if `global` is set as `window`. I now pushed the change to main branch.
